networks:
  fleetsim-net:
    external: true  # 外部网络，Jenkins先判断 没有会自动创建

services:
  fleetsim-backend:
    env_file:
      - .env.prod
    environment:
      GIN_MODE: release
    image: kirito693/fleetsim-backend:v0.1
    container_name: fleetsim-backend
    restart: unless-stopped
    ports:
      - "8088:8088"  # 宿主机:容器
    networks:
      - fleetsim-net
