definitions:
  common.Result:
    properties:
      code:
        description: 1表示成功 2表示失败
        type: integer
      data: {}
      message:
        type: string
    type: object
  model.Poi:
    properties:
      id:
        type: integer
      lat:
        type: number
      lon:
        type: number
      name:
        type: string
      status:
        type: integer
      tybe:
        type: integer
    type: object
  model.Vehicle:
    properties:
      categoryId:
        type: integer
      createTime:
        type: string
      id:
        type: integer
      lat:
        type: number
      license:
        type: string
      lon:
        type: number
      speed:
        type: number
      status:
        type: integer
      updateTime:
        type: string
    type: object
info:
  contact: {}
paths:
  /pois:
    get:
      consumes:
      - application/json
      description: 根据条件筛选/获取poi列表
      parameters:
      - description: poi名称
        in: query
        name: name
        type: string
      - description: poi类型
        in: query
        name: tybe
        type: integer
      - description: 状态
        in: query
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Result'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Poi'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Result'
      summary: 筛选/获取poi列表
      tags:
      - Poi
  /vehicles:
    get:
      consumes:
      - application/json
      description: 根据条件筛选/获取车辆列表
      parameters:
      - description: 车牌号
        in: query
        name: license
        type: string
      - description: 状态
        in: query
        name: status
        type: integer
      - description: 车辆类型
        in: query
        name: categoryId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Result'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Vehicle'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Result'
      summary: 筛选/获取车辆列表
      tags:
      - Vehicle
swagger: "2.0"
